{{if (eq .Channel.ParentID 635305499600093214)}}{{$o:=(dbGet .User.ID "Q").Value}}{{$e:=(dbGet .User.ID "admin").Value}}{{$j:=(dbGet .User.ID "age").Value}}{{$n:=(dbGet .User.ID "gt").Value}}{{$i:=(dbGet .User.ID "name").Value}}{{$k:=(dbGet .User.ID "pin").Value}}{{$c:=(dbGet .User.ID "public").Value}}{{$l:=(dbGet .User.ID "ref").Value}}{{$a:=(dbGet .User.ID "parentguardian").Value}}{{$f:=(dbGet .User.ID "tribe").Value}}{{if not $f}}{{$f ="Unregistered"}}{{end}}{{if not $o}}{{$o ="Edit Name"}}{{dbSet .User.ID "Q" $o}}{{sendMessage nil (joinStr "" .User.Mention ", how old are you?")}}{{else}}{{if eq (toString $o) "Age"}}{{if reFind `\D` (toString .Message.Content)}}{{sendMessage nil (joinStr "" "Sorry " .User.Mention ", thats not a number. I'll ask again, how old are you?")}}{{else if gt (toInt .Message.Content) 85}}{{sendMessage nil (joinStr "" "Sorry " .User.Mention ", that's an unrealistic number. I'll ask again, how old are you?")}}{{else if lt (toInt .Message.Content) 5}}{{sendMessage nil (joinStr "" "Sorry " .User.Mention ", that's an unrealistic number. I'll ask again, how old are you?")}}{{else}}{{$j =(toInt .Message.Content)}}{{dbSet .User.ID "age" $j}}
{{if ge $j 18}}{{$o ="GT"}}{{dbSet .User.ID "Q" $o}}{{sendMessage nil (joinStr "" .User.Mention ", what is your Gamer Tag?")}}{{else}}{{$o ="ParentGuardian"}}{{dbSet .User.ID "Q" $o}}{{$m:=sendMessageRetID nil (joinStr "" .User.Mention ", is your Parent or Guardian a member of this cluster?")}}{{addMessageReactions nil $m ":yes:658376626639339533" ":no:658376639322783745"}}{{end}}{{end}}{{else if eq (toString $o) "GT"}}{{$n =(toString .Message.Content)}}{{dbSet .User.ID "gt" $n}}{{$o ="Name"}}{{dbSet .User.ID "Q" $o}}{{sendMessage nil (joinStr "" .User.Mention ", what is your In Game Name?")}}
{{else if eq (toString $o) "Name"}}

{{$i =(toString .Message.Content)}}{{dbSet .User.ID "name" $i}}{{$o ="Ref"}}{{dbSet .User.ID "Q" $o}}{{$m:=sendMessageRetID nil (joinStr "" .User.Mention ", were you referred by one of our members?")}}{{addMessageReactions nil $m ":yes:658376626639339533" ":no:658376639322783745"}}{{else if eq (toString $o) "Ref2"}}{{$l =(toString (toString .Message.Content))}}{{dbSet .User.ID "ref" $l}}{{$o ="Pin"}}{{dbSet .User.ID "Q" $o}}{{sendMessage nil (joinStr "" .User.Mention ", what 4 digit pin would you like used whenever a pin may be required? (Quest Vaults, or other situations.)")}}{{else if eq (toString $o) "Pin"}}{{$k =(toString .Message.Content)}}{{dbSet .User.ID "pin" $k}}{{$o ="Starter"}}{{dbSet .User.ID "Q" $o}}{{$m:=sendMessageRetID nil (joinStr "" .User.Mention ", where would you like to pick up your starter?\n<:Artemis:640697096814592040> Artemis - Valguero (Main Map)\n<:Manticore:640697193052766218> Manticore - Ragnarok\n<:Gryphon:640697148807184384> Gryphon - Aberration\n<:Elysian:640698387506921523> Elysian - Center\n<:Zelda:640697492274544643> Zelda - Island\n<:Phoenix:640698407199178771> Phoenix - Scorched Earth\n<:Medusa:640697225684713473> Medusa - Extinction\n<:Titan:640697323143561276> Titan - Valguero\n<:Raiden:655954199476961300> Raiden - Ragnarok\n<:Beowulf:682592075685953570> Beowulf - Genesis\n⛔ No Starter Needed")}}{{addMessageReactions nil $m ":Artemis:640697096814592040" ":Manticore:640697193052766218" ":Gryphon:640697148807184384" ":Elysian:640698387506921523" ":Zelda:640697492274544643" ":Phoenix:640698407199178771" ":Medusa:640697225684713473" ":Titan:640697323143561276" ":Raiden:655954199476961300" "Beowulf:682592075685953570" "⛔"}}{{else if eq (toString $o) "ParentGuardian2"}}{{$a =(toString .Message.Content)}}{{dbSet .User.ID "parentguardian" $a}}{{$o ="GT2"}}{{dbSet .User.ID "Q" $o}}{{sendMessage nil (joinStr "" .User.Mention ", what is your Gamer Tag?")}}{{else if eq (toString $o) "GT2"}}{{$n =(toString .Message.Content)}}{{dbSet .User.ID "gt" $n}}{{$o ="Name2"}}{{dbSet .User.ID "Q" $o}}{{sendMessage nil (joinStr "" .User.Mention ", what is your In Game Name?")}}{{else if eq (toString $o) "Name2"}}{{$i =(toString .Message.Content)}}{{dbSet .User.ID "name" $i}}{{$o ="Pin2"}}{{dbSet .User.ID "Q" $o}}{{sendMessage nil (joinStr "" .User.Mention ", what 4 digit pin would you like used whenever a pin may be required? (Quest Vaults, or other situations.)")}}{{else if eq (toString $o) "Done"}}{{$o ="Done"}}{{dbSet .User.ID "Q" $o}}{{$g:=randInt 111111 999999}}{{$h:=cembed 
 "color" $g
 "fields" (cslice 
 (sdict "name" "In Game Name" "value" (toString $i) ) 
 (sdict "name" "Gamer Tag" "value" (toString $n) ) 
 (sdict "name" "Tribe Name" "value" (toString $f) ) )
 "thumbnail" (sdict "url" (.User.AvatarURL "1024"))}}{{$c =(toString (sendMessageRetID 658352884701724733 $h))}}{{dbSet .User.ID "public" $c}}{{editNickname (toString $i)}}{{$d:=cembed 
 "color" $g
 "fields" (cslice 
 (sdict "name" "Discord Name" "value" .User.Username ) 
 (sdict "name" "In Game Name" "value" (toString $i) ) 
 (sdict "name" "Gamer Tag" "value" (toString $n) ) 
 (sdict "name" "Referral" "value" (toString $l) ) 
 (sdict "name" "Pin" "value" (toString $k) ))
 "thumbnail" (sdict "url" (.User.AvatarURL "1024"))}}{{$e =(toString (sendMessageRetID 658354135221141533 $d))}}{{dbSet .User.ID "admin" $e}}{{giveRoleID .User.ID 573210479753691170}}{{giveRoleID .User.ID 607041870966685706}}{{removeRoleID 606566506922377257}}{{sendMessage 573245421066125324 (joinStr "" "Let's all welcome " .User.Mention " to the Cluster!")}}{{sendDM "Welcome to Yez's Ark Cluster! The password can be found on the #current-server-password channel, which you should now have access to. Please be aware that giving out this password is a ***bannable offense*** as is allowing people to piggyback off your login. To find the server make sure you are on unofficial PC sessions and have the password box checked. Do a search for Yez. Please be sure to read over the rules in the #pve-rules channel.\n\n__**Quests**__\nEvery week we offer *quests*, where you *collect*, **craft**, and __tame__ in order to receive rewards like bbs, coupons, element, and max level tames! We also offer ***new player quests*** until you hit level 100, which are designed to teach you how to play this game. If you are interested in participating, head over to #quest-rules, where you can read about how they work, and request a quest vault. \n\n__**Roles**__\nTo keep from pinging everyone, all the time, we've created various *Roles* for each of the things we usually ping people over. You can self-assign these roles by going to the #roles channel.\n\n__**Discord**__\nOur currency system is entirely Discord based, so having Discord is essential. **Leaving the Discord is seen as leaving the server.** If you leave the discord without contacting an admin, we will assume you have left, clearing your bases and confiscating your dinos for auction.\n\nWe hope you enjoy your time here at Yez's Ark Cluster. If you need any assistance, you can head over to #make-a-ticket."}}{{if .ExecData}}{{else}}{{sendMessageNoEscape nil (joinStr "" .User.Mention ": Stay turned to this channel! A member of the <@&634598489732546588> will be along as soon as possible to give you the information on how to get your starter.")}}{{end}}{{if eq (toString $l) "None"}}{{else}}{{$b:=sendMessageRetID 573860427721605120 (joinStr "" "Pay referral fee to " $l " for " $i)}}{{addMessageReactions 573860427721605120 $b "✔️" "❌"}}{{end}}{{else if eq (toString $o) "Pin2"}}{{$k =(toString .Message.Content)}}{{dbSet .User.ID "pin" $k}}{{$o ="Done"}}{{dbSet .User.ID "Q" $o}}{{$g:=randInt 111111 999999}}{{$h:=cembed 
 "color" $g
 "fields" (cslice 
 (sdict "name" "__***MINOR***__" "value" "_ _" ) 
 (sdict "name" "In Game Name" "value" (toString $i) ) 
 (sdict "name" "Tribe Name" "value" (toString $f) ) 
 (sdict "name" "Gamer Tag" "value" (toString $n) ) )
 "thumbnail" (sdict "url" (.User.AvatarURL "1024"))}}{{$c =(toString (sendMessageRetID 658352884701724733 $h))}}{{dbSet .User.ID "public" $c}}{{editNickname (joinStr "-" $i $a)}}{{$b:=sendMessageRetID 573860427721605120 (joinStr "" "Add Parent Role to  " $a " for " $i)}}{{addMessageReactions 573860427721605120 $b "✔️" "❌"}}{{$d:=cembed 
 "color" $g
 "fields" (cslice 
 (sdict "name" "Discord Name" "value" .User.Username ) 
 (sdict "name" "__***MINOR***__" "value" (toString (toInt $j)) ) 
 (sdict "name" "In Game Name" "value" (toString $i) ) 
 (sdict "name" "Gamer Tag" "value" (toString $n) ) 
 (sdict "name" "Tribe Name" "value" (toString $f) ) 
 (sdict "name" "Parent/Guardian" "value" (toString $a) )
 (sdict "name" "Pin" "value" (toString $k) ))
 "thumbnail" (sdict "url" (.User.AvatarURL "1024"))}}{{$e =(toString (sendMessageRetID 658354135221141533 $d))}}{{dbSet .User.ID "admin" $e}}{{giveRoleID .User.ID 645404993863811072}}{{removeRoleID 606566506922377257}}{{sendMessage nil (joinStr "" .User.Mention ", you are all set. Your parent/guardian should set you up with any gear you need. Please be sure to read through the rules for kids. Be aware that your parent/guardian is responsible for your actions. This channel will close in 60 seconds.")}}{{sleep 60}}{{exec "tickets close" "Registration Complete"}}{{end}}{{end}}{{end}}