{{if (eq .Channel.ParentID 635305499600093214)}} {{$reg := ""}}{{$msgID := .ReactionMessage.ID}}{{$db := dbGet .User.ID "registration"}}
{{if $db}}{{$reg = sdict}}{{range $k,$v := $db.Value}}{{$reg.Set $k $v}}{{end}}{{end}}
{{if (hasRoleID 607041870966685706)}}{{/*Has Registered Role*/}}
{{if and (eq .Reaction.Emoji.Name "1️⃣") (eq $reg.Q "Edit")}}{{$reg.Set "Q" "EN"}}{{dbSet .User.ID "registration" $reg}}{{deleteAllMessageReactions nil $msgID}}{{sendMessage nil (joinStr "" .User.Mention ", what's your *new* **in game name**?")}}
{{else if and (eq .Reaction.Emoji.Name "2️⃣") (eq $reg.Q "Edit")}}
{{$reg.Set "Q" "ET"}}{{dbSet .User.ID "registration" $reg}}{{deleteAllMessageReactions nil $msgID}}{{sendMessage nil (joinStr "" .User.Mention ", what's your *new* **tribe name**?")}}
{{else if and (eq .Reaction.Emoji.Name "3️⃣") (eq $reg.Q "Edit")}}{{$reg.Set "Q" "EG"}}{{dbSet .User.ID "registration" $reg}}{{deleteAllMessageReactions nil $msgID}}{{sendMessage nil (joinStr "" .User.Mention ", what's your *new* **Gamer Tag**?")}}
{{else if and (eq .Reaction.Emoji.Name "4️⃣") (eq $reg.Q "Edit")}}{{$reg.Set "Q" "EP"}}{{dbSet .User.ID "registration" $reg}}{{deleteAllMessageReactions nil $msgID}}{{sendMessage nil (joinStr "" .User.Mention ", what's your *new* **Pin**?")}}{{else if and (eq .Reaction.Emoji.Name "5️⃣") (eq $reg.Q "Edit")}}{{deleteAllMessageReactions nil $msgID}}{{$reg.Set "Q" "Edit"}}{{dbSet .User.ID "registration" $reg}}{{execCC 74 nil 0 ""}}{{removeRoleID 658469834589208616}}{{sleep 3}}{{exec "tickets close" "Done Editing Registration"}}
{{else if and (eq .Reaction.Emoji.ID 658376626639339533) (eq $reg.Q "EE")}}{{deleteAllMessageReactions nil $msgID}}{{$reg.Set "Q" "Edit"}}{{dbSet .User.ID "registration" $reg}}{{execCC 73 nil 0 ""}}
{{else if and (eq .Reaction.Emoji.ID 658376639322783745) (eq $reg.Q "EE")}}{{deleteAllMessageReactions nil $msgID}}{{$reg.Set "Q" "Edit"}}{{dbSet .User.ID "registration" $reg}}{{execCC 74 nil 0 ""}}{{sleep 3}}{{removeRoleID 658469834589208616}}{{exec "tickets close" "Done Editing Registration"}}
{{else if (eq .Reaction.Emoji.Name "gcrystal")}}{{deleteAllMessageReactions nil $msgID}}{{exec "tickets close" "Picked up Items"}}{{end}}
{{else if hasRoleID 645404993863811072}}{{/*Has Kids Role*/}}
{{if and (eq .Reaction.Emoji.Name "1️⃣") (eq $reg.Q "Edit")}}{{$reg.Set "Q" "EN"}}{{dbSet .User.ID "registration" $reg}}{{deleteAllMessageReactions nil $msgID}}{{sendMessage nil (joinStr "" .User.Mention ", what's your *new* **in game name**?")}}
{{else if and (eq .Reaction.Emoji.Name "2️⃣") (eq $reg.Q "Edit")}}{{$reg.Set "Q" "ET"}}{{dbSet .User.ID "registration" $reg}}{{deleteAllMessageReactions nil $msgID}}{{sendMessage nil (joinStr "" .User.Mention ", what's your *new* **tribe name**?")}}
{{else if and (eq .Reaction.Emoji.Name "3️⃣") (eq $reg.Q "Edit")}}{{$reg.Set "Q" "EG"}}{{dbSet .User.ID "registration" $reg}}{{deleteAllMessageReactions nil $msgID}}{{sendMessage nil (joinStr "" .User.Mention ", what's your *new* **Gamer Tag**?")}}
{{else if and (eq .Reaction.Emoji.Name "4️⃣") (eq $reg.Q "Edit")}}
{{$reg.Set "Q" "EP"}}{{dbSet .User.ID "registration" $reg}}{{deleteAllMessageReactions nil $msgID}}{{sendMessage nil (joinStr "" .User.Mention ", what's your *new* **Pin**?")}}
{{else if (eq .Reaction.Emoji.Name "gcrystal")}}{{deleteAllMessageReactions nil $msgID}}{{exec "tickets close" "Picked up Items"}}
{{else if and (eq .Reaction.Emoji.Name "5️⃣") (eq $reg.Q "Edit")}}{{$reg.Set "Q" "EA"}}{{dbSet .User.ID "registration" $reg}}{{deleteAllMessageReactions nil $msgID}}{{$msg := sendMessageRetID nil (joinStr "" .User.Mention ", did you have a birthday?")}}{{addMessageReactions nil $msg ":yes:658376626639339533" ":no:658376639322783745"}}
{{else if and (eq .Reaction.Emoji.Name "6️⃣") (eq $reg.Q "Edit")}}{{$reg.Set "Q" "EPG"}}{{dbSet .User.ID "registration" $reg}}{{deleteAllMessageReactions nil $msgID}}{{sendMessage nil (joinStr "" .User.Mention ", who's your *new* **Parent/Guardian**?")}}
{{else if and (eq .Reaction.Emoji.Name "7️⃣") (eq $reg.Q "Edit")}}{{deleteAllMessageReactions nil $msgID}}{{$reg.Set "Q" "Edit"}}{{dbSet .User.ID "registration" $reg}}{{execCC 74 nil 0 ""}}{{removeRoleID 658469834589208616}}{{sleep 3}}{{exec "tickets close" "Done Editing Registration"}}
{{else if and (eq .Reaction.Emoji.ID 658376626639339533) (eq $reg.Q "EE")}}
{{deleteAllMessageReactions nil $msgID}}{{$reg.Set "Q" "Edit"}}{{dbSet .User.ID "registration" $reg}}{{execCC 73 nil 0 ""}}
{{else if and (eq .Reaction.Emoji.ID 658376639322783745) (eq $reg.Q "EE")}}
{{deleteAllMessageReactions nil $msgID}}{{$reg.Set "Q" "Edit"}}{{dbSet .User.ID "registration" $reg}}{{execCC 74 nil 0 ""}}
{{removeRoleID 658469834589208616}}{{sleep 3}}{{exec "tickets close" "Done Editing Registration"}}
{{else if and (eq .Reaction.Emoji.ID 658376626639339533) (eq $reg.Q "EA")}}{{deleteAllMessageReactions nil $msgID}}{{$reg.Set "Q" "EE"}}{{$reg.Set "age" (add (toInt $reg.age) 1)}}{{dbSet .User.ID "registration" $reg}}{{$msg := sendMessageRetID nil "Happy Birthday! Your age has been increased by 1. Did you want to edit anything else?"}}{{addMessageReactions nil $msg ":yes:658376626639339533" ":no:658376639322783745"}} 
{{else if and (eq .Reaction.Emoji.ID 658376639322783745) (eq $reg.Q "EA")}}{{deleteAllMessageReactions nil $msgID}}{{$reg.Set "Q" "EE"}}{{dbSet .User.ID "registration" $reg}}{{$msg := sendMessageRetID nil "Sorry, your age is not directly editable. If your age is incorrect, please have your guardian contact an admin to correct. If you are not underage, please contact an admin to have your registered role removed so you can re-register as an adult. Thanks. Did you want to edit anything else?"}}{{addMessageReactions nil $msg ":yes:658376626639339533" ":no:658376639322783745"}}{{end}}
{{else}}
{{if and (eq .Reaction.Emoji.ID 658376626639339533) (eq $reg.Q "R")}}{{deleteAllMessageReactions nil $msgID}}{{$reg.Set "Q" "R2"}}{{dbSet .User.ID "registration" $reg}}{{sendMessage nil (joinStr "" .User.Mention ", who referred you?")}}
{{else if and (eq .Reaction.Emoji.ID 658376639322783745) (eq $reg.Q "R")}}{{deleteAllMessageReactions nil $msgID}}{{$reg.Set "ref" "None"}}{{$reg.Set "Q" "P"}}{{dbSet .User.ID "registration" $reg}}{{sendMessage nil (joinStr "" .User.Mention ", what 4 digit pin would you like used whenever a pin may be required? (Quest Vaults, or other situations.)")}}
{{else if and (eq .Reaction.Emoji.ID 640697096814592040) (eq $reg.Q "S")}}{{deleteAllMessageReactions nil $msgID}}{{$reg.Set "Q" "D"}}{{dbSet .User.ID "registration" $reg}}{{execCC 71 nil 0 ""}}{{sendMessage nil "Selected Artemis"}}
{{else if and (eq .Reaction.Emoji.ID 640697193052766218) (eq $reg.Q "S")}}{{deleteAllMessageReactions nil $msgID}}{{$reg.Set "Q" "D"}}{{dbSet .User.ID "registration" $reg}}{{execCC 71 nil 0 ""}}{{sendMessage nil "Selected Manticore"}}
{{else if and (eq .Reaction.Emoji.ID 640697148807184384) (eq $reg.Q "S")}}{{deleteAllMessageReactions nil $msgID}}{{$reg.Set "Q" "D"}}{{dbSet .User.ID "registration" $reg}}{{execCC 71 nil 0 ""}}{{sendMessage nil "Selected Gryphon"}}
{{else if and (eq .Reaction.Emoji.ID 640698387506921523) (eq $reg.Q "S")}}{{deleteAllMessageReactions nil $msgID}}{{$reg.Set "Q" "D"}}{{dbSet .User.ID "registration" $reg}}{{execCC 71 nil 0 ""}}{{sendMessage nil "Selected Elysian"}}
{{else if and (eq .Reaction.Emoji.ID 640697492274544643) (eq $reg.Q "S")}}{{deleteAllMessageReactions nil $msgID}}{{$reg.Set "Q" "D"}}{{dbSet .User.ID "registration" $reg}}{{execCC 71 nil 0 ""}}{{sendMessage nil "Selected Zelda"}}
{{else if and (eq .Reaction.Emoji.ID 640698407199178771) (eq $reg.Q "S")}}{{deleteAllMessageReactions nil $msgID}}{{$reg.Set "Q" "D"}}{{dbSet .User.ID "registration" $reg}}{{execCC 71 nil 0 ""}}{{sendMessage nil "Selected Phoenix"}}
{{else if and (eq .Reaction.Emoji.ID 640697225684713473) (eq $reg.Q "S")}}{{deleteAllMessageReactions nil $msgID}}{{$reg.Set "Q" "D"}}{{dbSet .User.ID "registration" $reg}}{{execCC 71 nil 0 ""}}{{sendMessage nil "Selected Medusa"}}
{{else if and (eq .Reaction.Emoji.ID 640697323143561276) (eq $reg.Q "S")}}{{deleteAllMessageReactions nil $msgID}}{{$reg.Set "Q" "D"}}{{dbSet .User.ID "registration" $reg}}{{execCC 71 nil 0 ""}}{{sendMessage nil "Selected Titan"}}
{{else if and (eq .Reaction.Emoji.ID 655954199476961300) (eq $reg.Q "S")}}{{deleteAllMessageReactions nil $msgID}}{{$reg.Set "Q" "D"}}{{dbSet .User.ID "registration" $reg}}{{execCC 71 nil 0 ""}}{{sendMessage nil "Selected Raiden"}}
{{else if and (eq .Reaction.Emoji.ID 655954171844886558) (eq $reg.Q "S")}}{{deleteAllMessageReactions nil $msgID}}{{$reg.Set "Q" "D"}}{{dbSet .User.ID "registration" $reg}}{{execCC 71 nil 0 ""}}{{sendMessage nil "Selected Silvestria"}}
{{else if and (eq .Reaction.Emoji.Name "⛔") (eq $reg.Q "S")}}{{deleteAllMessageReactions nil $msgID}}{{$reg.Set "Q" "D"}}{{dbSet .User.ID "registration" $reg}}{{execCC 71 nil 0 ""}}{{sendMessage nil "No Starter Needed"}}
{{else if and (eq .Reaction.Emoji.ID 658376626639339533) (eq $reg.Q "PG")}}{{deleteAllMessageReactions nil $msgID}}{{$reg.Set "Q" "G2"}}{{dbSet .User.ID "registration" $reg}}{{sendMessage nil (joinStr "" .User.Mention ", who is your parent/guardian?")}}
{{else if and (eq .Reaction.Emoji.ID 658376639322783745) (eq $reg.Q "PG")}}{{deleteAllMessageReactions nil $msgID}}{{sendMessage nil (joinStr "" .User.Mention ": I'm sorry, but this cluster is for 18+ only. Please come back when you are over 18.")}}{{sendMessage 573897276569813012 (joinStr "" .User.Mention " is being kicked for being underage. Please take note in case they attempt to register again and lie.\n<@&573210843840249889>")}}{{sleep 10}}{{execAdmin "kick" .User.ID "Under age."}}{{execAdmin "tickets close underage"}}
{{end}}{{end}}{{end}}